const data = {
  products: [
    {
      name: "Zapatillas de diseño",
      slug: "zapatillas-diseño",
      category: "Calzado",
      image: "/images/zapatillas.png", // 679px × 829px
      price: 120,
      countInStock: 1,
      brand: "Martha Dibujante",
      rating: 4.5,
      numReviews: 10,
      description: "Zapatillas de diseño pintadas a mano por Martha",
    },
    {
      name: "Mesa decapada",
      slug: "mesa-decapada",
      category: "Muebles",
      image: "/images/mesa.png",
      price: 450,
      countInStock: 1,
      brand: "Pedro Carpintero",
      rating: 4.0,
      numReviews: 10,
      description: "Mesa anticuario decapada a mano",
    },
    {
      name: "Veleros de cerámica",
      slug: "veleros-ceramica",
      category: "Decoración",
      image: "/images/veleros.png",
      price: 25,
      countInStock: 1,
      brand: "Sophia Arte-sana",
      rating: 4.5,
      numReviews: 14,
      description: "Dos veleros hechos a mano con cerámica",
    },
    {
      name: "Ramo de flores secas",
      slug: "flores-secas",
      category: "Decoración",
      image: "/images/flores.png",
      price: 25,
      countInStock: 1,
      brand: "Carla´s flowers",
      rating: 4.5,
      numReviews: 10,
      description: "Ramo de flores secas hecho a mano",
    },
    {
      name: "2 hojas de Origami",
      slug: "hojas-origami",
      category: "Decoración",
      image: "/images/origami.png",
      price: 15,
      countInStock: 1,
      brand: "Carla´s flowers",
      rating: 4.5,
      numReviews: 10,
      description: "Dos hojas de papel origami hechas a mano",
    },
    {
      name: "Jabón Natural",
      slug: "jabon-natural",
      category: "Hogar",
      image: "/images/jabon.png",
      price: 9,
      countInStock: 1,
      brand: "Manuela`s shop",
      rating: 4.5,
      numReviews: 10,
      description: "Jabón de Hierbabuena artesanal",
    },
    {
      name: "Pulseras",
      slug: "pulseras",
      category: "Bisutería",
      image: "/images/pulseras.png",
      price: 30,
      countInStock: 1,
      brand: "Bijou Carol",
      rating: 4.5,
      numReviews: 10,
      description: "Pulseras artesanales",
    },
    {
      name: "Galletas caseras",
      slug: "galletas",
      category: "Repostería",
      image: "/images/galletas.png",
      price: 3,
      countInStock: 1,
      brand: "Sara Pastelera",
      rating: 4.5,
      numReviews: 10,
      description: "Galletas caseras para Navidad",
    },
    {
      name: "Bufanda de hilo",
      slug: "bufanda",
      category: "Ropa",
      image: "/images/bufanda.png",
      price: 20,
      countInStock: 1,
      brand: "Paula Scarf",
      rating: 4.5,
      numReviews: 10,
      description: "Bufanda con hilo de algdón hecha a mano",
    },
    {
      name: "Cojín ganchillo",
      slug: "cojin",
      category: "Hogar",
      image: "/images/cojin.png",
      price: 28,
      countInStock: 1,
      brand: "Mariadeko",
      rating: 4.5,
      numReviews: 10,
      description: "Cojín de ganchillo hecho a mano",
    },
  ],
};
export default data;
